from __future__ import annotations

from PySide6.QtCore import Qt
from PySide6.QtWidgets import (
    QFrame,
    QHBoxLayout,
    QLabel,
    QPlainTextEdit,
    QProgressBar,
    QPushButton,
    QTabWidget,
    QVBoxLayout,
    QWidget,
)

from olhos_de_deus import __version__

from .animated_reference import AnimatedEye, AnimatedPlanet, ConsoleEye
from .cockpit_window import CockpitWindow


class ReferenceCockpitWindow(CockpitWindow):
    """Reference-faithful cockpit using the existing real controller and adapters."""

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.setWindowTitle("Olho de Deus · Cockpit de Inteligência Artificial")
        self.resize(1620, 970)
        self.setMinimumSize(1240, 760)

    def _build_sidebar(self) -> QWidget:
        sidebar = QFrame()
        sidebar.setObjectName("Sidebar")
        sidebar.setFixedWidth(220)
        layout = QVBoxLayout(sidebar)
        layout.setContentsMargins(10, 12, 10, 12)
        layout.setSpacing(4)

        self.sidebar_eye = AnimatedEye(compact=True)
        self.sidebar_eye.setFixedHeight(100)
        layout.addWidget(self.sidebar_eye)
        brand = QLabel("OLHO DE DEUS")
        brand.setObjectName("Brand")
        brand.setAlignment(Qt.AlignmentFlag.AlignCenter)
        subtitle = QLabel("INTELIGÊNCIA EM AÇÃO")
        subtitle.setObjectName("Subtitle")
        subtitle.setAlignment(Qt.AlignmentFlag.AlignCenter)
        layout.addWidget(brand)
        layout.addWidget(subtitle)
        layout.addSpacing(17)

        def nav(key: str, text: str, callback) -> None:
            button = QPushButton(text)
            button.setObjectName("NavButton")
            button.setCheckable(True)
            button.clicked.connect(callback)
            self._nav_buttons[key] = button
            layout.addWidget(button)

        nav("dashboard", "⌂   Dashboard", lambda: self._show_page("dashboard"))
        nav("missions", "◎   Missões", lambda: self._show_page("missions"))
        nav("integrations", "△   Integrações", lambda: self._show_page("integrations"))
        nav("ruflo", "◉   Ruflo", self._show_ruflo)
        nav("doctor", "✚   Doctor", lambda: self._show_page("doctor"))
        nav("logs", "▤   Logs", lambda: self._show_page("logs"))
        nav("settings", "⚙   Configurações", lambda: self._show_page("settings"))
        layout.addStretch(1)

        quote = QLabel("“ MAIS INTELIGÊNCIA\n   PARA UM\n   MUNDO MELHOR ”")
        quote.setObjectName("CockpitQuote")
        layout.addWidget(quote)
        layout.addSpacing(8)
        version = QLabel(f"◉  OLHO DE DEUS v{__version__}\n    SISTEMA OPERACIONAL DE INTELIGÊNCIA")
        version.setObjectName("SidebarFooter")
        version.setWordWrap(True)
        layout.addWidget(version)
        return sidebar

    def _build_dashboard_page(self) -> QWidget:
        page = QWidget()
        outer = QHBoxLayout(page)
        outer.setContentsMargins(12, 10, 12, 10)
        outer.setSpacing(10)

        center = QVBoxLayout()
        center.setSpacing(8)
        outer.addLayout(center, 1)

        top = QFrame()
        top.setObjectName("CockpitTopBar")
        top_layout = QHBoxLayout(top)
        top_layout.setContentsMargins(7, 5, 7, 5)
        top_layout.setSpacing(5)
        item, self.cockpit_system = self._status_item("●", "STATUS GERAL", "ONLINE")
        top_layout.addWidget(item)
        item, self.cockpit_version = self._status_item("◉", "VERSÃO", f"v{__version__}")
        top_layout.addWidget(item)
        item, self.cockpit_agent = self._status_item("✺", "AGENTE ATIVO", "Ruflo")
        top_layout.addWidget(item)
        item, self.cockpit_mission = self._status_item("◎", "MISSÃO ATUAL", "Aguardando")
        top_layout.addWidget(item, 2)
        model = QLabel("MODELO 2 — COCKPIT")
        model.setObjectName("CockpitModel")
        top_layout.addWidget(model)
        center.addWidget(top)

        hero = QFrame()
        hero.setObjectName("HeroBanner")
        hero_layout = QHBoxLayout(hero)
        hero_layout.setContentsMargins(16, 5, 16, 5)
        hero_layout.setSpacing(8)
        hero_text = QVBoxLayout()
        hero_text.setSpacing(1)
        for line in ("VER MAIS.", "PENSAR MAIS.", "REALIZAR MAIS."):
            label = QLabel(line)
            label.setObjectName("HeroTitle")
            hero_text.addWidget(label)
        hero_layout.addLayout(hero_text)
        self.hero_visual = AnimatedPlanet()
        hero_layout.addWidget(self.hero_visual, 1)
        quote = QLabel("“ DADOS HOJE.\n  UM AMANHÃ MELHOR. ”")
        quote.setObjectName("HeroQuote")
        quote.setAlignment(Qt.AlignmentFlag.AlignRight | Qt.AlignmentFlag.AlignVCenter)
        hero_layout.addWidget(quote)
        center.addWidget(hero)

        command = QFrame()
        command.setObjectName("CommandCard")
        command_layout = QVBoxLayout(command)
        command_layout.setContentsMargins(14, 10, 14, 10)
        command_layout.setSpacing(7)
        head = QHBoxLayout()
        title = QLabel("✣  COMANDO CENTRAL")
        title.setObjectName("SectionTitle")
        head.addWidget(title)
        head.addStretch(1)
        meta = QLabel("LINGUAGEM NATURAL   •   MULTIAGENTES   •   RESULTADOS REAIS")
        meta.setObjectName("CockpitMeta")
        head.addWidget(meta)
        command_layout.addLayout(head)

        self.quick_mission = QPlainTextEdit()
        self.quick_mission.setObjectName("CommandInput")
        self.quick_mission.setMaximumHeight(120)
        self.quick_mission.setPlaceholderText("O que você quer que o Olho de Deus faça?")
        command_layout.addWidget(self.quick_mission)

        buttons = QHBoxLayout()
        execute = QPushButton("▶   EXECUTAR     Enter")
        execute.setObjectName("PrimaryButton")
        execute.clicked.connect(self._run_quick_mission)
        plan = QPushButton("▣   PLANEJAR")
        plan.setObjectName("SecondaryButton")
        plan.clicked.connect(lambda: self._prepare_mission(""))
        research = QPushButton("⌕   PESQUISAR")
        research.setObjectName("SecondaryButton")
        research.clicked.connect(lambda: self._prepare_mission("Pesquisar e analisar: "))
        create = QPushButton("＋   CRIAR")
        create.setObjectName("SecondaryButton")
        create.clicked.connect(lambda: self._prepare_mission("Criar: "))
        more = QPushButton("•••")
        more.setObjectName("SecondaryButton")
        buttons.addWidget(execute)
        buttons.addWidget(plan)
        buttons.addWidget(research)
        buttons.addWidget(create)
        buttons.addWidget(more)
        buttons.addStretch(1)
        command_layout.addLayout(buttons)
        center.addWidget(command)

        response = QFrame()
        response.setObjectName("ResponseCard")
        response_layout = QVBoxLayout(response)
        response_layout.setContentsMargins(12, 9, 12, 9)
        response_layout.setSpacing(5)
        response_head = QHBoxLayout()
        response_title = QLabel(">_  RESPOSTA / EXECUÇÃO")
        response_title.setObjectName("SectionTitle")
        self.cockpit_execution_state = QLabel("● EXECUÇÃO EM TEMPO REAL")
        self.cockpit_execution_state.setObjectName("Ready")
        response_head.addWidget(response_title)
        response_head.addStretch(1)
        response_head.addWidget(self.cockpit_execution_state)
        response_layout.addLayout(response_head)

        self.cockpit_tabs = QTabWidget()
        self.cockpit_tabs.setObjectName("CockpitTabs")
        self.dashboard_output = ConsoleEye()
        self.dashboard_output.setReadOnly(True)
        self.dashboard_output.setObjectName("ConsoleOutput")
        self.dashboard_logs = QPlainTextEdit()
        self.dashboard_logs.setReadOnly(True)
        self.dashboard_logs.setObjectName("ConsoleOutput")
        self.dashboard_results = QPlainTextEdit()
        self.dashboard_results.setReadOnly(True)
        self.dashboard_results.setObjectName("ConsoleOutput")
        files_placeholder = QPlainTextEdit()
        files_placeholder.setReadOnly(True)
        files_placeholder.setObjectName("ConsoleOutput")
        files_placeholder.setPlainText("Arquivos produzidos por executores reais aparecerão aqui.")
        agents_placeholder = QPlainTextEdit()
        agents_placeholder.setReadOnly(True)
        agents_placeholder.setObjectName("ConsoleOutput")
        agents_placeholder.setPlainText("Atividade de agentes aparecerá aqui quando houver runtime externo configurado.\nNenhuma atividade é simulada.")
        self.cockpit_tabs.addTab(self.dashboard_output, "HISTÓRICO")
        self.cockpit_tabs.addTab(self.dashboard_logs, "LOGS")
        self.cockpit_tabs.addTab(self.dashboard_results, "RESULTADOS")
        self.cockpit_tabs.addTab(files_placeholder, "ARQUIVOS")
        self.cockpit_tabs.addTab(agents_placeholder, "PENSAMENTO DOS AGENTES")
        response_layout.addWidget(self.cockpit_tabs, 1)

        bottom = QHBoxLayout()
        command_line = QLabel("Digite uma mensagem ou comando...")
        command_line.setObjectName("CommandBar")
        bottom.addWidget(command_line, 1)
        send = QPushButton("➤")
        send.setObjectName("SendButton")
        send.clicked.connect(self._run_quick_mission)
        bottom.addWidget(send)
        response_layout.addLayout(bottom)
        center.addWidget(response, 1)

        operations = QFrame()
        operations.setObjectName("OperationsPanel")
        operations.setFixedWidth(320)
        operations_layout = QVBoxLayout(operations)
        operations_layout.setContentsMargins(10, 10, 10, 10)
        operations_layout.setSpacing(8)
        panel_title = QLabel("⌁  PAINEL DE OPERAÇÕES")
        panel_title.setObjectName("SectionTitle")
        operations_layout.addWidget(panel_title)

        card, card_layout = self._operation_card("✺  Ruflo", "Agente principal")
        self.ops_ruflo = QLabel("Verificando...")
        self.ops_ruflo.setObjectName("ReadyBadge")
        self.ops_ruflo_detail = QLabel("")
        self.ops_ruflo_detail.setObjectName("Muted")
        self.ops_ruflo_detail.setWordWrap(True)
        open_ruflo = QPushButton("ABRIR RUFLO")
        open_ruflo.setObjectName("SecondaryButton")
        open_ruflo.clicked.connect(self._show_ruflo)
        card_layout.addWidget(self.ops_ruflo)
        card_layout.addWidget(self.ops_ruflo_detail)
        card_layout.addWidget(open_ruflo)
        operations_layout.addWidget(card)

        card, card_layout = self._operation_card("△  Swarm", "Equipe de agentes")
        self.ops_swarm = QLabel("Verificando...")
        self.ops_swarm.setObjectName("PendingBadge")
        self.ops_swarm_detail = QLabel("Estado real do workspace Ruflo")
        self.ops_swarm_detail.setObjectName("Muted")
        self.ops_swarm_detail.setWordWrap(True)
        self.swarm_progress = QProgressBar()
        self.swarm_progress.setObjectName("HudProgress")
        self.swarm_progress.setRange(0, 100)
        self.swarm_progress.setValue(0)
        self.swarm_progress.setTextVisible(False)
        card_layout.addWidget(self.ops_swarm)
        card_layout.addWidget(self.ops_swarm_detail)
        card_layout.addWidget(self.swarm_progress)
        operations_layout.addWidget(card)

        card, self.agents_card_layout = self._operation_card("♙  Agentes Ativos", "Estado real do runtime")
        self.ops_agents = QLabel("Nenhum runtime externo confirmado")
        self.ops_agents.setObjectName("Muted")
        self.ops_agents.setWordWrap(True)
        self.agents_card_layout.addWidget(self.ops_agents)
        operations_layout.addWidget(card)

        card, self.integrations_card_layout = self._operation_card("⌁  Integrações", "7 fases operacionais")
        self.ops_integrations = QLabel("0 / 7 READY")
        self.ops_integrations.setObjectName("ReadyBadge")
        self.ops_integrations_detail = QLabel("")
        self.ops_integrations_detail.setObjectName("Muted")
        self.ops_integrations_detail.setWordWrap(True)
        manage = QPushButton("GERENCIAR")
        manage.setObjectName("SecondaryButton")
        manage.clicked.connect(lambda: self._show_page("integrations"))
        self.integrations_card_layout.addWidget(self.ops_integrations)
        self.integrations_card_layout.addWidget(self.ops_integrations_detail)
        self.integrations_card_layout.addWidget(manage)
        operations_layout.addWidget(card)

        world = QFrame()
        world.setObjectName("WorldCard")
        world_layout = QHBoxLayout(world)
        world_layout.setContentsMargins(10, 7, 10, 7)
        world_label = QLabel("INTELIGÊNCIA\nSEM FRONTEIRAS")
        world_label.setObjectName("WorldLabel")
        world_layout.addWidget(world_label)
        mini_eye = AnimatedEye(compact=True)
        mini_eye.setFixedHeight(62)
        world_layout.addWidget(mini_eye, 1)
        operations_layout.addWidget(world)
        operations_layout.addStretch(1)
        outer.addWidget(operations)
        return page

    def _run_quick_mission(self) -> None:
        working = bool(self.quick_mission.toPlainText().strip())
        if working:
            self.sidebar_eye.set_working(True)
            self.hero_visual.set_working(True)
            self.dashboard_output.set_working(True)
        super()._run_quick_mission()

    def _cockpit_mission_finished(self, result: object) -> None:
        super()._cockpit_mission_finished(result)
        self.sidebar_eye.set_working(False)
        self.hero_visual.set_working(False)
        self.dashboard_output.set_working(False)

    def _cockpit_mission_failed(self, message: str) -> None:
        super()._cockpit_mission_failed(message)
        self.sidebar_eye.set_working(False)
        self.hero_visual.set_working(False)
        self.dashboard_output.set_working(False)
